
CREATE TABLE expenses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_id INTEGER
        REFERENCES types(id) ON DELETE CASCADE NOT NULL, 
    amount decimal(14,2) NOT NULL, 
    name TEXT NOT NULL, 
    description TEXT NOT NULL, 
    date DATE NOT NULL, 
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);