
CREATE TABLE serviceproviders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_id INTEGER
        REFERENCES types(id) ON DELETE CASCADE NOT NULL, 
    name TEXT NOT NULL, 
    description TEXT NOT NULL, 
    telephone TEXT NOT NULL, 
    email TEXT NOT NULL, 
    address_id INTEGER 
        REFERENCES addresses(id) ON DELETE CASCADE NOT NULL, 
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);